version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tws_db
    volumes: 
      - ./mysql-data:/var/lib/mysql
    networks:
      - twotiernet
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD","mysqladmin","-h","localhost","-uroot","-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tws_db
    depends_on:
      - mysql
    networks:
      - twotiernet
    restart: always

networks:
  twotiernet:
volumes: 
  mysql-data:
